---
title: "Poster Graphics"
output: html_notebook
---


Load Packages and Data

```{r}
## Load packages
library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)
library(cowplot)
library(pracma)
library(RColorBrewer)
library(EnhancedVolcano)
library(gridExtra)
library(pals)

memory.limit(size = 16000000)

## Integrated PDAC datasets 
load("C:\\Users\\Ryan\\Documents\\Nie Research Project\\GSE 155698\\PDAC155698.integrated")

## BCCIO dataset
load("C:\\Users\\Ryan\\Documents\\Nie Research Project\\GSE 123813\\BCCIOwithUMAP")

## Merged dataset (5000 cells from PDAC and BCC, random sample)
load("C:\\Users\\Ryan\\Documents\\Nie Research Project\\BCC.PDAC.merge")

## Load functions
source("ClusteringAnalysisFunctions.R", echo=TRUE)
source("SeuratClusteringFunctions.R", echo=TRUE)

```



BCC Clustering UMAP

```{r}

BCCIO <- RenameIdents(object = BCCIO, 
                      'CD8_memory' = 'CD8+ memory T cells',
                      'CD4' = 'CD4+ T cells', 
                      'Tregs' = 'Regulatory T cells',
                      'CD8_activation' = 'CD8+ activated T cells',
                      'CD8_exhausted' = 'CD8+ exhausted T cells',
                      'Plasma' = 'Plasma cells',
                      'Tumor 1' = 'Malignant cells 1',
                      'Tumor 2' = 'Malignant cells 2',
                      'T_proliferation' = 'Proliferating T cells',
                      'NK' = 'NK cells',
                      'Endothelial' = 'Endothelial cells',
                      'DCs' = 'Dendritic cells',
                      'Misc.' = 'Other')

BCC.UMAP <- DimPlot(object = BCCIO, 
                    reduction ="umap", 
                    label = TRUE, 
                    pt.size = 0.3,
                    label.size = 6) + NoLegend()
BCC.UMAP

## Default dimensions, width = 1200px
## Saved as BCC_UMAP.jpeg

```



BCC UMAP separated by patient

```{r}

BCC.UMAP.patient <- DimPlot(object = BCCIO,
                            reduction = "umap",
                            label = FALSE,
                            split.by = c("patient"),
                            pt.size = 0.1,
                            ncol = 6)
BCC.UMAP.patient

## Dimensions: width = 1500px, height = 505px
## Post-processing to remove axes in powerpoint
## Saved as BCC_UMAP_Patient.JPG

```



BCC UMAP separated by responders vs. nonresponders

```{r}

BCC.UMAP.responder <- DimPlot(object = BCCIO,
                              reduction = "umap",
                              label = FALSE,
                              split.by = c("response"),
                              pt.size = 0.1,
                              ncol = 2)

BCC.UMAP.responder

## Dimensions: width = 1000px, height = 505px
## Saved as BCC_UMAP_Responder.jpeg

```



BCC UMAP separated by patient and treatment

```{r}

BCCIO$patient.treatment <- paste0(BCCIO$patient, BCCIO$treatment)

Idents(BCCIO) <- BCCIO$patient.treatment

BCC.patient001.pre.cells <- WhichCells(BCCIO, idents = c("su001pre"))
BCC.patient001.post.cells <- WhichCells(BCCIO, idents = c("su001post"))
BCC.patient002.pre.cells <- WhichCells(BCCIO, idents = c("su002pre"))
BCC.patient002.post.cells <- WhichCells(BCCIO, idents = c("su002post"))
BCC.patient003.pre.cells <- WhichCells(BCCIO, idents = c("su003pre"))
BCC.patient003.post.cells <- WhichCells(BCCIO, idents = c("su003post"))
BCC.patient004.pre.cells <- WhichCells(BCCIO, idents = c("su004pre"))
BCC.patient004.post.cells <- WhichCells(BCCIO, idents = c("su004post"))
BCC.patient005.pre.cells <- WhichCells(BCCIO, idents = c("su005pre"))
BCC.patient005.post.cells <- WhichCells(BCCIO, idents = c("su005post"))
BCC.patient006.pre.cells <- WhichCells(BCCIO, idents = c("su006pre"))
BCC.patient006.post.cells <- WhichCells(BCCIO, idents = c("su006post"))
BCC.patient007.pre.cells <- WhichCells(BCCIO, idents = c("su007pre"))
BCC.patient007.post.cells <- WhichCells(BCCIO, idents = c("su007post"))
BCC.patient008.pre.cells <- WhichCells(BCCIO, idents = c("su008pre"))
BCC.patient008.post.cells <- WhichCells(BCCIO, idents = c("su008post"))
BCC.patient009.pre.cells <- WhichCells(BCCIO, idents = c("su009pre"))
BCC.patient009.post.cells <- WhichCells(BCCIO, idents = c("su009post"))
BCC.patient010.pre.cells <- WhichCells(BCCIO, idents = c("su010pre"))
BCC.patient010.post.cells <- WhichCells(BCCIO, idents = c("su010post"))
BCC.patient012.pre.cells <- WhichCells(BCCIO, idents = c("su012pre"))
BCC.patient012.post.cells <- WhichCells(BCCIO, idents = c("su012post"))

BCC.UMAP.patient1.treatment <- DimPlot(object = BCCIO,
                                      reduction = "umap", 
                                      label = FALSE,
                                      group.by = c("patient.treatment"),
                                      cells.highlight = list(BCC.patient001.pre.cells, BCC.patient001.post.cells),
                                      cols.highlight = c("royalblue1", "darkslategray1"),
                                      cols = c("grey90"),
                                      sizes.highlight = 0.1,
                                      pt.size = 0.1) + NoLegend() + 
                                      labs(title = "su001", x = "",  y = "") + 
                                      theme(axis.line.y = element_blank(), axis.line.x = element_blank(),
                                            axis.text.y = element_blank(), axis.text.x = element_blank(),
                                            axis.ticks.y = element_blank(), axis.ticks.x = element_blank(),
                                            plot.title = element_text(hjust = 0.5))
BCC.UMAP.patient2.treatment <- DimPlot(object = BCCIO,
                                      reduction = "umap", 
                                      label = FALSE,
                                      group.by = c("patient.treatment"),
                                      cells.highlight = list(BCC.patient002.pre.cells, BCC.patient002.post.cells),
                                      cols.highlight = c("royalblue1", "darkslategray1"),
                                      cols = c("grey90"),
                                      sizes.highlight = 0.1,
                                      pt.size = 0.1) + NoLegend() + 
                                      labs(title = "su002", x = "",  y = "") + 
                                      theme(axis.line.y = element_blank(), axis.line.x = element_blank(),
                                            axis.text.y = element_blank(), axis.text.x = element_blank(),
                                            axis.ticks.y = element_blank(), axis.ticks.x = element_blank(),
                                            plot.title = element_text(hjust = 0.5))
BCC.UMAP.patient3.treatment <- DimPlot(object = BCCIO,
                                      reduction = "umap", 
                                      label = FALSE,
                                      group.by = c("patient.treatment"),
                                      cells.highlight = list(BCC.patient003.pre.cells, BCC.patient003.post.cells),
                                      cols.highlight = c("royalblue1", "darkslategray1"),
                                      cols = c("grey90"),
                                      sizes.highlight = 0.1,
                                      pt.size = 0.1) + NoLegend() + 
                                      labs(title = "su003", x = "",  y = "") + 
                                      theme(axis.line.y = element_blank(), axis.line.x = element_blank(),
                                            axis.text.y = element_blank(), axis.text.x = element_blank(),
                                            axis.ticks.y = element_blank(), axis.ticks.x = element_blank(),
                                            plot.title = element_text(hjust = 0.5))
BCC.UMAP.patient4.treatment <- DimPlot(object = BCCIO,
                                      reduction = "umap", 
                                      label = FALSE,
                                      group.by = c("patient.treatment"),
                                      cells.highlight = list(BCC.patient004.pre.cells, BCC.patient004.post.cells),
                                      cols.highlight = c("royalblue1", "darkslategray1"),
                                      cols = c("grey90"),
                                      sizes.highlight = 0.1,
                                      pt.size = 0.1) + NoLegend() + 
                                      labs(title = "su004", x = "",  y = "") + 
                                      theme(axis.line.y = element_blank(), axis.line.x = element_blank(),
                                            axis.text.y = element_blank(), axis.text.x = element_blank(),
                                            axis.ticks.y = element_blank(), axis.ticks.x = element_blank(),
                                            plot.title = element_text(hjust = 0.5))
BCC.UMAP.patient5.treatment <- DimPlot(object = BCCIO,
                                      reduction = "umap", 
                                      label = FALSE,
                                      group.by = c("patient.treatment"),
                                      cells.highlight = list(BCC.patient005.pre.cells, BCC.patient005.post.cells),
                                      cols.highlight = c("royalblue1", "darkslategray1"),
                                      cols = c("grey90"),
                                      sizes.highlight = 0.1,
                                      pt.size = 0.1) + NoLegend() + 
                                      labs(title = "su005", x = "",  y = "") + 
                                      theme(axis.line.y = element_blank(), axis.line.x = element_blank(),
                                            axis.text.y = element_blank(), axis.text.x = element_blank(),
                                            axis.ticks.y = element_blank(), axis.ticks.x = element_blank(),
                                            plot.title = element_text(hjust = 0.5))
BCC.UMAP.patient6.treatment <- DimPlot(object = BCCIO,
                                      reduction = "umap", 
                                      label = FALSE,
                                      group.by = c("patient.treatment"),
                                      cells.highlight = list(BCC.patient006.pre.cells, BCC.patient006.post.cells),
                                      cols.highlight = c("royalblue1", "darkslategray1"),
                                      cols = c("grey90"),
                                      sizes.highlight = 0.1,
                                      pt.size = 0.1) + NoLegend() + 
                                      labs(title = "su006", x = "",  y = "") + 
                                      theme(axis.line.y = element_blank(), axis.line.x = element_blank(),
                                            axis.text.y = element_blank(), axis.text.x = element_blank(),
                                            axis.ticks.y = element_blank(), axis.ticks.x = element_blank(),
                                            plot.title = element_text(hjust = 0.5))
BCC.UMAP.patient7.treatment <- DimPlot(object = BCCIO,
                                      reduction = "umap", 
                                      label = FALSE,
                                      group.by = c("patient.treatment"),
                                      cells.highlight = list(BCC.patient007.pre.cells, BCC.patient007.post.cells),
                                      cols.highlight = c("royalblue1", "darkslategray1"),
                                      cols = c("grey90"),
                                      sizes.highlight = 0.1,
                                      pt.size = 0.1) + NoLegend() + 
                                      labs(title = "su007", x = "",  y = "") + 
                                      theme(axis.line.y = element_blank(), axis.line.x = element_blank(),
                                            axis.text.y = element_blank(), axis.text.x = element_blank(),
                                            axis.ticks.y = element_blank(), axis.ticks.x = element_blank(),
                                            plot.title = element_text(hjust = 0.5))
BCC.UMAP.patient8.treatment <- DimPlot(object = BCCIO,
                                      reduction = "umap", 
                                      label = FALSE,
                                      group.by = c("patient.treatment"),
                                      cells.highlight = list(BCC.patient008.pre.cells, BCC.patient008.post.cells),
                                      cols.highlight = c("royalblue1", "darkslategray1"),
                                      cols = c("grey90"),
                                      sizes.highlight = 0.1,
                                      pt.size = 0.1) + NoLegend() + 
                                      labs(title = "su008", x = "",  y = "") + 
                                      theme(axis.line.y = element_blank(), axis.line.x = element_blank(),
                                            axis.text.y = element_blank(), axis.text.x = element_blank(),
                                            axis.ticks.y = element_blank(), axis.ticks.x = element_blank(),
                                            plot.title = element_text(hjust = 0.5))
BCC.UMAP.patient9.treatment <- DimPlot(object = BCCIO,
                                      reduction = "umap", 
                                      label = FALSE,
                                      group.by = c("patient.treatment"),
                                      cells.highlight = list(BCC.patient009.pre.cells, BCC.patient009.post.cells),
                                      cols.highlight = c("royalblue1", "darkslategray1"),
                                      cols = c("grey90"),
                                      sizes.highlight = 0.1,
                                      pt.size = 0.1) + NoLegend() + 
                                      labs(title = "su009", x = "",  y = "") + 
                                      theme(axis.line.y = element_blank(), axis.line.x = element_blank(),
                                            axis.text.y = element_blank(), axis.text.x = element_blank(),
                                            axis.ticks.y = element_blank(), axis.ticks.x = element_blank(),
                                            plot.title = element_text(hjust = 0.5))
BCC.UMAP.patient10.treatment <- DimPlot(object = BCCIO,
                                      reduction = "umap", 
                                      label = FALSE,
                                      group.by = c("patient.treatment"),
                                      cells.highlight = list(BCC.patient010.pre.cells, BCC.patient010.post.cells),
                                      cols.highlight = c("royalblue1", "darkslategray1"),
                                      cols = c("grey90"),
                                      sizes.highlight = 0.1,
                                      pt.size = 0.1) + NoLegend() + 
                                      labs(title = "su010", x = "",  y = "") + 
                                      theme(axis.line.y = element_blank(), axis.line.x = element_blank(),
                                            axis.text.y = element_blank(), axis.text.x = element_blank(),
                                            axis.ticks.y = element_blank(), axis.ticks.x = element_blank(),
                                            plot.title = element_text(hjust = 0.5))
BCC.UMAP.patient12.treatment <- DimPlot(object = BCCIO,
                                      reduction = "umap", 
                                      label = FALSE,
                                      group.by = c("patient.treatment"),
                                      cells.highlight = list(BCC.patient012.pre.cells, BCC.patient012.post.cells),
                                      cols.highlight = c("royalblue1", "darkslategray1"),
                                      cols = c("grey90"),
                                      sizes.highlight = 0.1,
                                      pt.size = 0.1) + NoLegend() + 
                                      labs(title = "su012", x = "",  y = "") + 
                                      theme(axis.line.y = element_blank(), axis.line.x = element_blank(),
                                            axis.text.y = element_blank(), axis.text.x = element_blank(),
                                            axis.ticks.y = element_blank(), axis.ticks.x = element_blank(),
                                            plot.title = element_text(hjust = 0.5))

BCC.UMAP.patient.treatment <- grid.arrange(BCC.UMAP.patient1.treatment, BCC.UMAP.patient2.treatment, BCC.UMAP.patient3.treatment, BCC.UMAP.patient4.treatment, BCC.UMAP.patient5.treatment, BCC.UMAP.patient6.treatment, BCC.UMAP.patient7.treatment, BCC.UMAP.patient8.treatment, BCC.UMAP.patient9.treatment, BCC.UMAP.patient10.treatment, BCC.UMAP.patient12.treatment,  nrow=2)

BCC.UMAP.patient.treatment

## Dimensions: width = 1500px, height = 500px
## Post-processing to add legend in Powerpoint
## Saved as: BCC_UMAP_Patient_Treatment.JPG

```



BCC Clustering Marker Genes

```{r}

BCC.cluster.order <- c('CD4+ T cells', 'CD8+ memory T cells', 'CD8+ activated T cells', 'CD8+ exhausted T cells', 'Proliferating T cells', 'Regulatory T cells', 'NK cells', 'B cells', 'Plasma cells', 'Macrophages', 'Dendritic cells', 'pDCs', 'Myofibroblasts', 'CAFs', 'Malignant cells 1', 'Malignant cells 2', 'Endothelial cells', 'Melanocytes', 'Other')

BCCIO <- RenameIdents(object = BCCIO, 
                      'CD4+ T cells' = 'CD4+ T cells', 
                      'CD8+ memory T cells' = 'CD8+ memory T cells',
                      'CD8+ activated T cells' = 'CD8+ activated T cells',
                      'CD8+ exhausted T cells' = 'CD8+ exhausted T cells',
                      'Proliferating T cells' = 'Proliferating T cells',
                      'Regulatory T cells' = 'Regulatory T cells',
                      'NK cells' = 'NK cells',
                      'B cells' = 'B cells',
                      'Plasma cells' = 'Plasma cells',
                      'Macrophages' = 'Macrophages',
                      'Dendritic cells' = 'Dendritic cells',
                      'pDCs' = 'pDCs', 
                      'Myofibroblasts' = 'Myofibroblasts',
                      'CAFs' = 'CAFs',
                      'Malignant cells 1' = 'Malignant cells 1',
                      'Malignant cells 2' = 'Malignant cells 2',
                      'Endothelial cells' = 'Endothelial cells',
                      'Melanocytes' = 'Melanocytes',
                      'Other' = 'Other')

features <- c('CD3D', 'CD3E', 'CD2', 'CD8A', 'GZMA', 'GZMB', 'CD4', 'FOXP3', 'KLRC1', 'KLRC3', 'NKG7', 'CD19', 'CD79A', 'SLAMF7', 'IGKC', 'FCGR2A', 'CSF1R', 'FLT3', 'CLEC4C', 'COL1A2', 'MCAM', 'MYLK', 'FAP', 'PDPN', 'EPCAM', 'TP63', 'PECAM1', 'VWF', 'PMEL', 'MLANA')

BCC.cluster.markers <- DotPlot(BCCIO, features = features, assay = 'RNA', cols = c('Azure', 'Blue')) + RotatedAxis() + xlab('Marker Genes')+ ylab('Clusters')

BCC.cluster.markers

## Dimensions: width = 1500px, height = 750px
## Saved as BCC_Cluster_Markers.jpeg

```



BCC 
